# coding: utf-8

"""
    Agent Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ap_client.models.run_update import RunUpdate

class TestRunUpdate(unittest.TestCase):
    """RunUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunUpdate:
        """Test RunUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunUpdate`
        """
        model = RunUpdate()
        if include_optional:
            return RunUpdate(
                command = ap_client.models.run_update_command.RunUpdate_command(
                    update = null, 
                    resume = null, 
                    goto = null, )
            )
        else:
            return RunUpdate(
        )
        """

    def testRunUpdate(self):
        """Test RunUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
