# coding: utf-8

"""
    Agent Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ap_client.models.send import Send

class TestSend(unittest.TestCase):
    """Send unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Send:
        """Test Send
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Send`
        """
        model = Send()
        if include_optional:
            return Send(
                node = '',
                input = ap_client.models.input.Input()
            )
        else:
            return Send(
                node = '',
                input = ap_client.models.input.Input(),
        )
        """

    def testSend(self):
        """Test Send"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
